version: "3.9"

services:
  lease-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - lease-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  lease-data:
